### ISSUE TITLE
some issuses about using sift_image_catg

### ISSUE THREAD

**Issue by paulxmq** [biswarajkar/sift_image_catg#1]
Hello teacher biswarajkar,i am also a student of cs my major image process and recognition .I confront some issues about using  sift_image_catg,I don't know there is some sepcial handle  before running the project.m .  I have read the readme.txt but that can't handle these problem,So I hope you give me some matters needing attention.the problems of running  the project.m are “wrong svm_classify (line 41)
   [W B] = vl_svmtrain(training_image_features', matching_indices, LAMBDA); wrong svm_classify (line 41)
    [W B] = vl_svmtrain(training_image_features', matching_indices, LAMBDA);”

**Comment by biswarajkar** [comment]
Hi Paul,

Thank you very much for pointing this out. Please check the latest commit, I have added a comma to the return statement, which was not needed in an older Matlab version, but it fails in new versions.  Please verify and let me know if you found any more issues.
